-- FloriWeb V3 RC2 - Bundle de atualizacao
-- PRE-REQUISITO: V3 RC1 ja aplicado e validado.
-- Execute este arquivo uma unica vez no Supabase SQL Editor.

-- ============================================================
-- 130 - Analytics anonimo
-- ============================================================
-- FloriWeb V3 RC2 - Analytics de conversao sem PII
-- Armazena somente loja, sessao anonima, evento, produto/pedido e horario.
-- Nao grava nome, telefone, e-mail, endereco, mensagem do cartao, observacoes ou IP.

begin;

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  store_id uuid not null references public.stores(id) on delete cascade,
  session_id uuid not null,
  event_name text not null,
  product_id uuid null references public.products(id) on delete set null,
  order_id uuid null references public.orders(id) on delete set null,
  occurred_at timestamptz not null default now(),
  constraint analytics_events_name_ck check (event_name in (
    'storefront_view',
    'product_view',
    'add_to_cart',
    'checkout_started',
    'order_created',
    'whatsapp_clicked'
  ))
);

create index if not exists analytics_events_store_time_idx
  on public.analytics_events(store_id, occurred_at desc);
create index if not exists analytics_events_store_session_idx
  on public.analytics_events(store_id, session_id, occurred_at desc);
create index if not exists analytics_events_product_idx
  on public.analytics_events(store_id, product_id, occurred_at desc)
  where product_id is not null;
create index if not exists analytics_events_order_idx
  on public.analytics_events(order_id)
  where order_id is not null;

alter table public.analytics_events enable row level security;
revoke all on public.analytics_events from public, anon, authenticated;
revoke all on sequence public.analytics_events_id_seq from public, anon, authenticated;

-- Eventos de navegacao aceitos do storefront. A funcao faz deduplicacao de curto prazo
-- para evitar inflar metricas por re-render/reload acidental da SPA.
create or replace function public.track_public_event_v3(
  p_store_id uuid,
  p_session_id uuid,
  p_event_name text,
  p_product_id uuid default null
)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_window interval;
  v_product_id uuid := p_product_id;
begin
  if p_store_id is null or p_session_id is null then
    raise exception 'Evento invalido.' using errcode='P0001';
  end if;

  if p_event_name not in ('storefront_view','product_view','add_to_cart','checkout_started') then
    raise exception 'Evento nao permitido.' using errcode='P0001';
  end if;

  if not public.store_accessible(p_store_id) then
    return;
  end if;

  if p_event_name in ('product_view','add_to_cart') then
    if v_product_id is null or not exists (
      select 1
      from public.products p
      join public.categories c
        on c.id = p.category_id
       and c.store_id = p.store_id
      where p.id = v_product_id
        and p.store_id = p_store_id
        and p.active
        and c.active
    ) then
      raise exception 'Produto invalido para telemetria.' using errcode='P0001';
    end if;
  else
    v_product_id := null;
  end if;

  v_window := case p_event_name
    when 'storefront_view' then interval '30 minutes'
    when 'product_view' then interval '10 minutes'
    when 'add_to_cart' then interval '1 minute'
    when 'checkout_started' then interval '15 minutes'
    else interval '1 minute'
  end;

  if exists (
    select 1
    from public.analytics_events ae
    where ae.store_id = p_store_id
      and ae.session_id = p_session_id
      and ae.event_name = p_event_name
      and ae.product_id is not distinct from v_product_id
      and ae.occurred_at >= now() - v_window
  ) then
    return;
  end if;

  insert into public.analytics_events(store_id, session_id, event_name, product_id)
  values (p_store_id, p_session_id, p_event_name, v_product_id);
end;
$$;

revoke all on function public.track_public_event_v3(uuid,uuid,text,uuid) from public;
grant execute on function public.track_public_event_v3(uuid,uuid,text,uuid) to anon, authenticated;

-- Relatorio agregado: somente administradores da propria loja e apenas em plano com reports=true.
create or replace function public.get_store_analytics_v3(
  p_store_id uuid,
  p_from timestamptz default null,
  p_to timestamptz default null
)
returns jsonb
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
declare
  v_from timestamptz := coalesce(p_from, now() - interval '30 days');
  v_to timestamptz := coalesce(p_to, now());
  v_storefront_sessions bigint := 0;
  v_product_views bigint := 0;
  v_product_view_sessions bigint := 0;
  v_add_sessions bigint := 0;
  v_checkout_sessions bigint := 0;
  v_order_sessions bigint := 0;
  v_orders bigint := 0;
  v_whatsapp bigint := 0;
  v_cart_abandoned bigint := 0;
  v_checkout_abandoned bigint := 0;
  v_revenue numeric := 0;
  v_average numeric := 0;
  v_top_products jsonb := '[]'::jsonb;
  v_viewed_not_sold jsonb := '[]'::jsonb;
begin
  if not public.is_store_admin(p_store_id) then
    raise exception 'Acesso negado.' using errcode='42501';
  end if;

  if not exists (
    select 1
    from public.store_subscriptions ss
    join public.plans p on p.id = ss.plan_id
    where ss.store_id = p_store_id
      and ss.status in ('trial','active')
      and p.active
      and p.reports
  ) then
    raise exception 'O plano atual nao inclui relatorios.' using errcode='42501';
  end if;

  if v_to > now() + interval '5 minutes' then v_to := now(); end if;
  if v_from >= v_to then raise exception 'Periodo de analytics invalido.' using errcode='P0001'; end if;
  if v_to - v_from > interval '180 days' then v_from := v_to - interval '180 days'; end if;

  select
    count(distinct session_id) filter (where event_name='storefront_view'),
    count(*) filter (where event_name='product_view'),
    count(distinct session_id) filter (where event_name='product_view'),
    count(distinct session_id) filter (where event_name='add_to_cart'),
    count(distinct session_id) filter (where event_name='checkout_started'),
    count(distinct session_id) filter (where event_name='order_created'),
    count(*) filter (where event_name='order_created'),
    count(*) filter (where event_name='whatsapp_clicked')
  into
    v_storefront_sessions,
    v_product_views,
    v_product_view_sessions,
    v_add_sessions,
    v_checkout_sessions,
    v_order_sessions,
    v_orders,
    v_whatsapp
  from public.analytics_events
  where store_id = p_store_id
    and occurred_at >= v_from
    and occurred_at < v_to;

  select count(distinct add_event.session_id)
  into v_cart_abandoned
  from public.analytics_events add_event
  where add_event.store_id = p_store_id
    and add_event.event_name='add_to_cart'
    and add_event.occurred_at >= v_from
    and add_event.occurred_at < v_to
    and not exists (
      select 1
      from public.analytics_events order_event
      where order_event.store_id = p_store_id
        and order_event.session_id = add_event.session_id
        and order_event.event_name='order_created'
        and order_event.occurred_at >= v_from
        and order_event.occurred_at < v_to
    );

  select count(distinct checkout_event.session_id)
  into v_checkout_abandoned
  from public.analytics_events checkout_event
  where checkout_event.store_id = p_store_id
    and checkout_event.event_name='checkout_started'
    and checkout_event.occurred_at >= v_from
    and checkout_event.occurred_at < v_to
    and not exists (
      select 1
      from public.analytics_events order_event
      where order_event.store_id = p_store_id
        and order_event.session_id = checkout_event.session_id
        and order_event.event_name='order_created'
        and order_event.occurred_at >= v_from
        and order_event.occurred_at < v_to
    );

  select
    coalesce(sum(o.total) filter (where o.status <> 'cancelled'),0),
    coalesce(avg(o.total) filter (where o.status <> 'cancelled'),0)
  into v_revenue, v_average
  from public.orders o
  where o.store_id = p_store_id
    and o.created_at >= v_from
    and o.created_at < v_to;

  with views as (
    select product_id, count(*)::bigint as views
    from public.analytics_events
    where store_id=p_store_id
      and event_name='product_view'
      and product_id is not null
      and occurred_at >= v_from and occurred_at < v_to
    group by product_id
  ), adds as (
    select product_id, count(distinct session_id)::bigint as add_sessions
    from public.analytics_events
    where store_id=p_store_id
      and event_name='add_to_cart'
      and product_id is not null
      and occurred_at >= v_from and occurred_at < v_to
    group by product_id
  ), sold as (
    select oi.product_id, coalesce(sum(oi.quantity),0)::bigint as sold_units
    from public.order_items oi
    join public.orders o on o.id=oi.order_id
    where o.store_id=p_store_id
      and o.status <> 'cancelled'
      and o.created_at >= v_from and o.created_at < v_to
      and oi.product_id is not null
    group by oi.product_id
  ), ranked as (
    select p.id, p.name,
      coalesce(v.views,0)::bigint as views,
      coalesce(a.add_sessions,0)::bigint as add_sessions,
      coalesce(s.sold_units,0)::bigint as sold_units
    from public.products p
    left join views v on v.product_id=p.id
    left join adds a on a.product_id=p.id
    left join sold s on s.product_id=p.id
    where p.store_id=p_store_id
      and (coalesce(v.views,0)>0 or coalesce(a.add_sessions,0)>0 or coalesce(s.sold_units,0)>0)
    order by coalesce(v.views,0) desc, coalesce(a.add_sessions,0) desc, coalesce(s.sold_units,0) desc, p.name
    limit 8
  )
  select coalesce(jsonb_agg(jsonb_build_object(
    'productId', id,
    'name', name,
    'views', views,
    'addToCartSessions', add_sessions,
    'soldUnits', sold_units
  )), '[]'::jsonb)
  into v_top_products
  from ranked;

  with views as (
    select product_id, count(*)::bigint as views
    from public.analytics_events
    where store_id=p_store_id
      and event_name='product_view'
      and product_id is not null
      and occurred_at >= v_from and occurred_at < v_to
    group by product_id
  ), adds as (
    select product_id, count(distinct session_id)::bigint as add_sessions
    from public.analytics_events
    where store_id=p_store_id
      and event_name='add_to_cart'
      and product_id is not null
      and occurred_at >= v_from and occurred_at < v_to
    group by product_id
  ), sold as (
    select oi.product_id, coalesce(sum(oi.quantity),0)::bigint as sold_units
    from public.order_items oi
    join public.orders o on o.id=oi.order_id
    where o.store_id=p_store_id
      and o.status <> 'cancelled'
      and o.created_at >= v_from and o.created_at < v_to
      and oi.product_id is not null
    group by oi.product_id
  ), ranked as (
    select p.id, p.name,
      coalesce(v.views,0)::bigint as views,
      coalesce(a.add_sessions,0)::bigint as add_sessions,
      coalesce(s.sold_units,0)::bigint as sold_units
    from public.products p
    join views v on v.product_id=p.id
    left join adds a on a.product_id=p.id
    left join sold s on s.product_id=p.id
    where p.store_id=p_store_id
      and coalesce(v.views,0)>0
      and coalesce(s.sold_units,0)=0
    order by coalesce(v.views,0) desc, coalesce(a.add_sessions,0) desc, p.name
    limit 8
  )
  select coalesce(jsonb_agg(jsonb_build_object(
    'productId', id,
    'name', name,
    'views', views,
    'addToCartSessions', add_sessions,
    'soldUnits', sold_units
  )), '[]'::jsonb)
  into v_viewed_not_sold
  from ranked;

  return jsonb_build_object(
    'from', v_from,
    'to', v_to,
    'storefrontSessions', v_storefront_sessions,
    'productViews', v_product_views,
    'productViewSessions', v_product_view_sessions,
    'addToCartSessions', v_add_sessions,
    'checkoutSessions', v_checkout_sessions,
    'orderSessions', v_order_sessions,
    'orders', v_orders,
    'whatsappClicks', v_whatsapp,
    'conversionRate', case when v_storefront_sessions>0 then round((v_order_sessions::numeric/v_storefront_sessions::numeric)*100,1) else 0 end,
    'cartAbandonmentRate', case when v_add_sessions>0 then round((v_cart_abandoned::numeric/v_add_sessions::numeric)*100,1) else 0 end,
    'checkoutAbandonmentRate', case when v_checkout_sessions>0 then round((v_checkout_abandoned::numeric/v_checkout_sessions::numeric)*100,1) else 0 end,
    'whatsappRate', case when v_orders>0 then round((v_whatsapp::numeric/v_orders::numeric)*100,1) else 0 end,
    'revenue', round(v_revenue,2),
    'averageTicket', round(v_average,2),
    'topProducts', v_top_products,
    'viewedNotSold', v_viewed_not_sold
  );
end;
$$;

revoke all on function public.get_store_analytics_v3(uuid,timestamptz,timestamptz) from public;
grant execute on function public.get_store_analytics_v3(uuid,timestamptz,timestamptz) to authenticated;

commit;

-- ============================================================
-- 140 - Checkout via Edge + Turnstile
-- ============================================================
-- FloriWeb V3 RC2 - Checkout somente pela Edge Function + fingerprint explicito
-- A validacao Turnstile ocorre em supabase/functions/public-checkout.
-- Depois desta migration, anon/authenticated nao executam create_public_order diretamente.

begin;

create or replace function public.enforce_public_order_rate_limit(p_store_id uuid)
returns void
language plpgsql
security definer
set search_path = public, private, pg_temp
as $$
declare
  v_headers jsonb := '{}'::jsonb;
  v_ip text := '';
  v_salt text := '';
  v_fingerprint text := '';
  v_explicit_fingerprint text := '';
  v_count integer := 0;
begin
  begin
    v_headers := coalesce(nullif(current_setting('request.headers', true), '')::jsonb, '{}'::jsonb);
  exception when others then
    v_headers := '{}'::jsonb;
  end;

  -- A Edge Function publica calcula SHA-256 do cliente e envia somente o hash.
  -- Como create_public_order deixa de ser executavel por anon/authenticated, este
  -- header nao pode ser usado pelo navegador para trocar de fingerprint e burlar o limite.
  v_explicit_fingerprint := lower(trim(coalesce(v_headers->>'x-floriweb-security-fingerprint','')));
  if v_explicit_fingerprint ~ '^[a-f0-9]{64}$' then
    v_fingerprint := v_explicit_fingerprint;
  else
    v_ip := nullif(trim(coalesce(v_headers->>'cf-connecting-ip','')), '');
    if v_ip is null then
      v_ip := nullif(trim(split_part(coalesce(v_headers->>'x-forwarded-for',''), ',', 1)), '');
    end if;

    -- Chamadas internas/SQL Editor nao devem ser bloqueadas por falta de contexto HTTP.
    if v_ip is null then return; end if;

    select value into v_salt
    from private.floriweb_security_settings
    where key='public_order_rate_limit_salt';

    if coalesce(v_salt,'') = '' then
      raise exception 'Configuracao interna de seguranca ausente.' using errcode='P0001';
    end if;
    v_fingerprint := md5(v_ip || ':' || v_salt);
  end if;

  perform pg_advisory_xact_lock(hashtextextended(p_store_id::text || ':' || v_fingerprint, 0));

  select count(*) into v_count
  from private.public_order_rate_limits rl
  where rl.store_id = p_store_id
    and rl.fingerprint = v_fingerprint
    and rl.request_at >= now() - interval '10 minutes';

  if v_count >= 8 then
    raise exception 'Muitas tentativas de pedido em pouco tempo. Aguarde alguns minutos e tente novamente.' using errcode='P0001';
  end if;

  insert into private.public_order_rate_limits(store_id,fingerprint)
  values (p_store_id,v_fingerprint);

  delete from private.public_order_rate_limits
  where request_at < now() - interval '24 hours';
end;
$$;

revoke all on function public.enforce_public_order_rate_limit(uuid) from public, anon, authenticated;

-- Impede bypass do Turnstile chamando a RPC diretamente pelo navegador.
revoke all on function public.create_public_order(jsonb) from public, anon, authenticated;
grant execute on function public.create_public_order(jsonb) to service_role;

-- Captura a abertura do WhatsApp usando a mesma sessao anonima ligada ao pedido.
create or replace function public.capture_whatsapp_analytics_v3()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_session_id uuid;
begin
  if new.whatsapp_clicked_at is null or old.whatsapp_clicked_at is not null then
    return new;
  end if;

  select ae.session_id into v_session_id
  from public.analytics_events ae
  where ae.order_id = new.id
    and ae.event_name = 'order_created'
  order by ae.occurred_at desc
  limit 1;

  if v_session_id is not null and not exists (
    select 1 from public.analytics_events ae
    where ae.order_id = new.id and ae.event_name='whatsapp_clicked'
  ) then
    insert into public.analytics_events(store_id,session_id,event_name,order_id,occurred_at)
    values(new.store_id,v_session_id,'whatsapp_clicked',new.id,coalesce(new.whatsapp_clicked_at,now()));
  end if;
  return new;
end;
$$;

revoke all on function public.capture_whatsapp_analytics_v3() from public, anon, authenticated;

drop trigger if exists orders_whatsapp_analytics_v3_trg on public.orders;
create trigger orders_whatsapp_analytics_v3_trg
after update of whatsapp_clicked_at on public.orders
for each row execute function public.capture_whatsapp_analytics_v3();

commit;

-- ============================================================
-- 145 - Idempotencia do checkout
-- ============================================================
-- FloriWeb V3 RC2 - Idempotencia do checkout publico
-- Evita pedido duplicado quando o banco grava com sucesso, mas a resposta ao cliente se perde.

begin;

alter table public.orders
  add column if not exists public_request_id uuid null;

create unique index if not exists orders_store_public_request_uidx
  on public.orders(store_id, public_request_id)
  where public_request_id is not null;

create or replace function private.capture_public_order_request_id()
returns trigger
language plpgsql
security definer
set search_path = public, private, pg_temp
as $$
declare
  v_headers jsonb := '{}'::jsonb;
  v_request_id text := '';
begin
  begin
    v_headers := coalesce(nullif(current_setting('request.headers', true), '')::jsonb, '{}'::jsonb);
  exception when others then
    v_headers := '{}'::jsonb;
  end;

  v_request_id := lower(trim(coalesce(v_headers->>'x-floriweb-request-id','')));
  if v_request_id ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' then
    new.public_request_id := v_request_id::uuid;
  end if;
  return new;
end;
$$;

revoke all on function private.capture_public_order_request_id() from public, anon, authenticated;

drop trigger if exists orders_public_request_id_trg on public.orders;
create trigger orders_public_request_id_trg
before insert on public.orders
for each row execute function private.capture_public_order_request_id();

comment on column public.orders.public_request_id is 'UUID tecnico de idempotencia do checkout publico; nao contem dados pessoais.';

commit;

-- ============================================================
-- 150 - Diagnostico RC2
-- ============================================================
-- FloriWeb V3 RC2 - Diagnostico da plataforma atualizado
-- Mantem o diagnostico somente para Admin Master AAL2 e inclui telemetria anonima.

begin;

create or replace function public.platform_system_check()
returns jsonb
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
declare
  result jsonb;
  v_duration integer := 30;
  v_warning integer := 7;
  v_cron_scheduled boolean := false;
begin
  if not public.is_platform_admin() then
    raise exception 'Acesso restrito ao Admin Master.' using errcode='42501';
  end if;

  select demo_duration_days,demo_warning_days into v_duration,v_warning
  from public.platform_settings where id=1;

  if to_regnamespace('cron') is not null then
    begin
      execute 'select exists(select 1 from cron.job where jobname = ''floriweb-expire-demo-trials'')' into v_cron_scheduled;
    exception when others then
      v_cron_scheduled := false;
    end;
  end if;

  select jsonb_build_object(
    'version', '3.0.0-rc.2',
    'platformAdmin', true,
    'stores', (select count(*) from public.stores where archived_at is null),
    'storesOnline', (select count(*) from public.stores where archived_at is null and public.store_accessible(id)),
    'storesSuspended', (select count(*) from public.stores where archived_at is null and not public.store_accessible(id)),
    'plans', (select count(*) from public.plans),
    'subscriptions', (select count(*) from public.store_subscriptions),
    'users', (select count(*) from public.store_users),
    'products', (select count(*) from public.products),
    'orders', (select count(*) from public.orders),
    'deliveryZones', (select count(*) from public.delivery_zones),
    'domains', (select count(*) from public.store_domains),
    'analyticsEvents', (select count(*) from public.analytics_events),
    'demoTrials', (
      select count(*) from public.store_subscriptions ss
      join public.plans p on p.id=ss.plan_id
      where p.code='DEMO' and ss.status='trial'
    ),
    'demoTrialsExpiringSoon', (
      select count(*) from public.store_subscriptions ss
      join public.plans p on p.id=ss.plan_id
      where p.code='DEMO' and ss.status='trial' and ss.expires_at is not null
        and ss.expires_at > now()
        and ss.expires_at <= now() + make_interval(days => v_warning)
    ),
    'demoDurationDays', v_duration,
    'demoWarningDays', v_warning,
    'demoCronScheduled', v_cron_scheduled
  ) into result;

  return result;
end;
$$;

revoke all on function public.platform_system_check() from public;
grant execute on function public.platform_system_check() to authenticated;

commit;
