import fs from 'node:fs';
import path from 'node:path';
const root=process.cwd();
const read=(p)=>fs.readFileSync(path.join(root,p),'utf8');
const exists=(p)=>fs.existsSync(path.join(root,p));
const failures=[];
const ok=(name,condition)=>{console.log(`${condition?'OK  ':'ERRO'} ${name}`);if(!condition)failures.push(name)};
const pkg=JSON.parse(read('package.json'));
const types=read('src/types/index.ts');
const settings=read('src/pages/admin/Settings.tsx');
const finance=read('src/pages/admin/Finance.tsx');
const orders=read('src/pages/admin/Orders.tsx');
const header=read('src/components/StoreHeader.tsx');
const success=read('src/pages/store/OrderSuccess.tsx');
const master=read('src/layouts/MasterLayout.tsx');
const styles=read('src/styles.css');
ok('Versao 3.0.0-rc.6.11',pkg.version==='3.0.0-rc.6.11');
ok('Pausa de almoco no tipo',types.includes('breakStart?: string')&&types.includes('breakEnd?: string'));
ok('Recebimento preservado no pedido',types.includes("OrderPaymentStatus = 'pending' | 'paid'")&&types.includes('paymentStatus: OrderPaymentStatus')&&types.includes('paymentReceivedAt?: string'));
ok('Pedidos preservam confirmacao de recebimento',orders.includes('Confirmar recebimento')&&orders.includes('confirmOrderPayment'));
ok('Pedidos preservam atualizacao automatica',orders.includes('setInterval')&&orders.includes('visibilitychange')&&/reloadAdmin\(\{\s*silent\s*:\s*true\s*\}\)/.test(orders));
ok('Configuracao de almoco no admin',settings.includes('Fechar para almoço')&&settings.includes('breakStart')&&settings.includes('breakEnd'));
ok('Pedidos com filtro e ordenacao',orders.includes('orders-toolbar--filters')&&orders.includes('Ordenar por')&&orders.includes('statusFilter'));
ok('Pedido relacionado usa highlight',finance.includes('/admin/pedidos?highlight=')&&orders.includes('order-row-highlighted'));
ok('Horario mostra hoje e outros dias',header.includes('<b>Hoje</b>')&&header.includes('Outros dias')&&header.includes('store-hours-popover'));
ok('Popover fecha fora e com ESC',header.includes("document.addEventListener('pointerdown'")&&header.includes("event.key==='Escape'")&&header.includes('hoursRef'));
ok('PIX copia e cola tem acao visivel',success.includes('aria-label="Copiar PIX"')&&success.includes('title="Copiar PIX"'));
ok('Admin Master import correto do suporte',master.includes("import PlatformHelpButton from '../components/PlatformHelpButton'"));
ok('CSS possui camada do popover',styles.includes('store-hours-popover')&&styles.includes('store-hours-details__list'));
ok('Favicon RC6.11 existe',exists('public/favicon-floriweb-rc611.svg')&&read('index.html').includes('favicon-floriweb-rc611.svg'));
if(failures.length){console.error(`\nRC6.11 com ${failures.length} falha(s).`);process.exit(1)}
console.log('\nRC6.11 pronta para validacao e publicacao.');
