import { Loader2, MessageCircle, ShieldCheck, X } from 'lucide-react';
import { useCallback, useState, type ReactNode } from 'react';
import { appConfig } from '../lib/config';
import { requestPublicContact, type PublicContactIntent } from '../services/publicContactApi';
import { TurnstileWidget } from './ui/TurnstileWidget';

export default function ProtectedContactButton({className='',intent='commercial',children}:{className?:string;intent?:PublicContactIntent;children?:ReactNode}){
  const[open,setOpen]=useState(false);const[token,setToken]=useState('');const[loading,setLoading]=useState(false);const[error,setError]=useState('');const[reset,setReset]=useState(0);
  const receive=useCallback((value:string)=>{setToken(value);setError('')},[]);
  const proceed=async()=>{if(!appConfig.turnstileSiteKey){setError('A proteção anti-robô ainda não foi configurada.');return}if(!token){setError('Conclua a verificação de segurança.');return}const popup=window.open('about:blank','_blank');try{setLoading(true);const url=await requestPublicContact(token,intent);if(popup){popup.opener=null;popup.location.replace(url)}else{window.location.assign(url)}setOpen(false);setToken('')}catch(e){if(popup&&!popup.closed)popup.close();setError(e instanceof Error?e.message:'Não foi possível abrir o contato.');setReset((v)=>v+1)}finally{setLoading(false)}};
  return <><button type="button" className={className} onClick={()=>setOpen(true)}>{children||<><MessageCircle size={17}/>Falar no WhatsApp</>}</button>{open&&<div className="flori-contact-overlay" role="dialog" aria-modal="true"><div className="flori-contact-card"><button type="button" className="flori-contact-close" onClick={()=>!loading&&setOpen(false)} aria-label="Fechar"><X size={18}/></button><div className="flori-contact-icon"><ShieldCheck/></div><span className="eyebrow">CONTATO PROTEGIDO</span><h2>Confirme que você é uma pessoa</h2><p>O telefone comercial não fica exposto na página. A validação é feita antes de abrir o WhatsApp.</p>{appConfig.turnstileSiteKey?<TurnstileWidget siteKey={appConfig.turnstileSiteKey} action="marketing" onToken={receive} resetSignal={reset}/>:<div className="form-error">Turnstile não configurado neste build.</div>}{error&&<div className="form-error">{error}</div>}<button className="primary-button" type="button" onClick={()=>void proceed()} disabled={loading||!token}>{loading?<><Loader2 className="spin"/>Validando...</>:<><MessageCircle/>Continuar no WhatsApp</>}</button></div></div>}</>;
}
