import { ArrowLeft, ImagePlus, Plus, Save, Star, Trash2, X } from 'lucide-react';
import { useEffect, useMemo, useState, type FormEvent } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { ImageWithFallback } from '../../components/ui/ImageWithFallback';
import { LoadingState } from '../../components/ui/AsyncState';
import { useStore } from '../../contexts/StoreContext';
import { useToast } from '../../contexts/ToastContext';
import type { Product, ProductImage, ProductVariation } from '../../types';
import { currency, slugify } from '../../utils/format';
import { createId } from '../../utils/id';

const newVariation=(index:number):ProductVariation=>({id:createId(),name:'',priceDelta:0,active:true,sortOrder:(index+1)*10});
const emptyProduct=(storeId:string):Product=>({id:createId(),storeId,slug:'',name:'',description:'',categoryId:'',price:0,promotionalPrice:undefined,imageUrl:'/assets/placeholder-flower.svg',gallery:[],images:[],featured:false,active:true,madeToOrder:false,productionDays:0,stockStatus:'available',variations:[],addons:[]});

export default function ProductForm(){
  const {id}=useParams();const {products,categories,addons,settings,saveProduct,uploadProductImages,deleteProductImage,setPrimaryImage,planUsage,loading}=useStore();const {showToast}=useToast();const navigate=useNavigate();const existing=products.find(p=>p.id===id);
  const [product,setProduct]=useState<Product>(()=>existing?structuredClone(existing):emptyProduct(settings.id));const[files,setFiles]=useState<File[]>([]);const[saving,setSaving]=useState(false);
  useEffect(()=>{if(id&&existing)setProduct(structuredClone(existing));else if(!id)setProduct(current=>current.storeId===settings.id?current:emptyProduct(settings.id))},[id,existing,settings.id]);
  const isNew=!id;const imageLimit=planUsage.plan.imageLimitPerProduct;const totalImages=product.images.length+files.length;
  const update=<K extends keyof Product>(key:K,value:Product[K])=>setProduct(p=>({...p,[key]:value}));
  const updateVariation=(variationId:string,patch:Partial<ProductVariation>)=>update('variations',product.variations.map(v=>v.id===variationId?{...v,...patch}:v));
  const toggleAddon=(addonId:string)=>{const addon=addons.find(a=>a.id===addonId);if(!addon)return;update('addons',product.addons.some(a=>a.id===addonId)?product.addons.filter(a=>a.id!==addonId):[...product.addons,addon])};
  const activeCategories=useMemo(()=>categories.filter(c=>c.active||c.id===product.categoryId),[categories,product.categoryId]);
  const selectFiles=(list:FileList|null)=>{if(!list)return;const next=Array.from(list);if(imageLimit!=null&&totalImages+next.length>imageLimit){showToast(`Seu plano permite até ${imageLimit} imagens por produto.`,'error');return}setFiles(current=>[...current,...next])};
  const submit=async(e:FormEvent)=>{e.preventDefault();if(saving)return;const activationConsumesSlot=product.active&&(!existing||!existing.active);if(activationConsumesSlot&&!planUsage.canActivateProduct){showToast(`Seu plano permite até ${planUsage.plan.productLimit} produtos ativos. Salve este produto como oculto ou desative outro item antes de publicá-lo.`,'error');return}if(product.promotionalPrice!=null&&product.promotionalPrice>product.price){showToast('O preço promocional não pode ser maior que o preço normal.','error');return}const basePrice=product.promotionalPrice??product.price;if(product.variations.some((variation)=>basePrice+variation.priceDelta<0)){showToast('Uma variação está deixando o preço final negativo.','error');return}setSaving(true);try{const normalized:Product={...product,storeId:settings.id,slug:product.slug||slugify(product.name),productionDays:product.madeToOrder?Math.max(1,product.productionDays):0,variations:product.variations.filter(v=>v.name.trim()).map((v,index)=>({...v,name:v.name.trim(),sortOrder:(index+1)*10}))};await saveProduct(normalized);if(files.length){await uploadProductImages(normalized.id,files,normalized.images);setFiles([])}showToast(existing?'Produto atualizado.':'Produto cadastrado.','success');navigate('/admin/produtos')}catch(error){showToast(error instanceof Error?error.message:'Erro ao salvar produto.','error')}finally{setSaving(false)}};
  const removeImage=async(image:ProductImage)=>{if(!confirm('Excluir esta imagem?'))return;try{await deleteProductImage(image);setProduct(p=>({...p,images:p.images.filter(i=>i.id!==image.id)}));showToast('Imagem removida.','success')}catch(e){showToast(e instanceof Error?e.message:'Erro ao remover imagem.','error')}};
  const primary=async(image:ProductImage)=>{try{await setPrimaryImage(product.id,image.id);setProduct(p=>({...p,images:p.images.map(i=>({...i,isPrimary:i.id===image.id})),imageUrl:image.url}));showToast('Imagem principal atualizada.','success')}catch(e){showToast(e instanceof Error?e.message:'Erro ao definir imagem.','error')}};
  if(loading)return <LoadingState label="Carregando produto..."/>;
  if(id&&!existing)return <div className="admin-card"><h2>Produto não encontrado</h2><Link to="/admin/produtos">Voltar</Link></div>;
  return <><div className="admin-page-title"><div><Link to="/admin/produtos" className="back-link"><ArrowLeft size={16}/>Produtos</Link><h1>{existing?'Editar produto':'Novo produto'}</h1><p>Informações, variações, adicionais e imagens exibidas ao cliente.</p></div></div><form className="admin-form-layout" onSubmit={submit}><section className="admin-card form-section"><div className="admin-card__header"><div><span className="eyebrow">INFORMAÇÕES</span><h2>Dados principais</h2></div></div><div className="form-grid"><label className="full">Nome do produto<input required value={product.name} onChange={e=>update('name',e.target.value)} placeholder="Ex.: Buquê Aurora"/></label><label>Categoria<select required value={product.categoryId} onChange={e=>update('categoryId',e.target.value)}><option value="">Selecione</option>{activeCategories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Status do estoque<select value={product.stockStatus} onChange={e=>update('stockStatus',e.target.value as Product['stockStatus'])}><option value="available">Disponível</option><option value="low_stock">Últimas unidades</option><option value="unavailable">Indisponível</option></select></label><label>Preço<input required type="number" min="0" step="0.01" value={product.price} onChange={e=>update('price',Number(e.target.value))}/></label><label>Preço promocional<input type="number" min="0" step="0.01" value={product.promotionalPrice??''} onChange={e=>update('promotionalPrice',e.target.value?Number(e.target.value):undefined)}/></label><label className="full">Descrição<textarea required rows={5} value={product.description} onChange={e=>update('description',e.target.value)}/></label></div>
    <div className="subform-section"><div className="subform-title"><div><span className="eyebrow">VARIAÇÕES</span><h3>Opções do produto</h3></div><button type="button" className="secondary-button" onClick={()=>update('variations',[...product.variations,newVariation(product.variations.length)])}><Plus size={16}/>Adicionar variação</button></div>{product.variations.length===0?<p className="muted">Sem variações. O produto será vendido pelo preço base.</p>:<div className="variation-editor">{product.variations.map((variation,index)=><div className="variation-row" key={variation.id}><input aria-label={`Nome da variação ${index+1}`} value={variation.name} onChange={e=>updateVariation(variation.id,{name:e.target.value})} placeholder="Ex.: Premium"/><div className="money-input"><span>R$</span><input aria-label={`Acréscimo da variação ${index+1}`} type="number" step="0.01" value={variation.priceDelta} onChange={e=>updateVariation(variation.id,{priceDelta:Number(e.target.value)})}/></div><label className="mini-check"><input type="checkbox" checked={variation.active} onChange={e=>updateVariation(variation.id,{active:e.target.checked})}/>Ativa</label><button type="button" className="row-delete" onClick={()=>update('variations',product.variations.filter(v=>v.id!==variation.id))}><Trash2 size={16}/></button></div>)}</div>}</div>
    <div className="subform-section"><span className="eyebrow">ADICIONAIS</span><h3>Complementos disponíveis</h3>{addons.length===0?<p className="muted">Cadastre adicionais no menu “Adicionais”.</p>:<div className="addon-picker">{addons.filter(a=>a.active||product.addons.some(p=>p.id===a.id)).map(addon=><label key={addon.id}><input type="checkbox" checked={product.addons.some(a=>a.id===addon.id)} onChange={()=>toggleAddon(addon.id)}/><span><strong>{addon.name}</strong><small>{currency.format(addon.price)}</small></span></label>)}</div>}</div>
    <div className="subform-section"><div className="subform-title"><div><span className="eyebrow">IMAGENS</span><h3>Galeria do produto</h3></div><span className="muted">{totalImages}/{imageLimit??'∞'} imagens</span></div><label className="upload-drop"><ImagePlus size={24}/><strong>Selecionar imagens</strong><span>JPG, PNG ou WEBP · até 5 MB cada</span><input type="file" multiple accept="image/jpeg,image/png,image/webp" onChange={e=>selectFiles(e.target.files)}/></label>{files.length>0&&<div className="pending-files">{files.map((file,index)=><span key={`${file.name}-${index}`}>{file.name}<button type="button" onClick={()=>setFiles(f=>f.filter((_,i)=>i!==index))}><X size={14}/></button></span>)}</div>}{product.images.length>0&&<div className="image-admin-grid">{product.images.map(image=><article key={image.id} className={image.isPrimary?'is-primary':''}><ImageWithFallback src={image.url} alt={image.altText||product.name}/><div><button type="button" onClick={()=>void primary(image)} title="Definir como principal"><Star size={16}/>{image.isPrimary?'Principal':'Tornar principal'}</button><button type="button" onClick={()=>void removeImage(image)} title="Excluir imagem"><Trash2 size={16}/></button></div></article>)}</div>}</div>
    </section><aside><section className="admin-card form-section"><span className="eyebrow">PUBLICAÇÃO</span><h2>Disponibilidade</h2><label className="switch-row"><span><strong>Produto ativo</strong><small>Aparece no catálogo público</small></span><input type="checkbox" checked={product.active} onChange={e=>update('active',e.target.checked)}/></label><label className="switch-row"><span><strong>Destaque</strong><small>Produto em evidência</small></span><input type="checkbox" checked={product.featured} onChange={e=>update('featured',e.target.checked)}/></label><label className="switch-row"><span><strong>Sob encomenda</strong><small>Exibe aviso de produção</small></span><input type="checkbox" checked={product.madeToOrder} onChange={e=>update('madeToOrder',e.target.checked)}/></label>{product.madeToOrder&&<label>Prazo de produção (dias)<input required type="number" min="1" value={product.productionDays||''} onChange={e=>update('productionDays',Number(e.target.value))}/></label>}</section><button className="primary-button full-button" disabled={saving} type="submit"><Save size={18}/>{saving?'Salvando...':'Salvar produto'}</button></aside></form></>;
}
