import fs from 'node:fs';
import path from 'node:path';
const root=process.cwd();
const read=(p)=>fs.readFileSync(path.join(root,p),'utf8');
const exists=(p)=>fs.existsSync(path.join(root,p));
const checks=[];const failures=[];const ok=(name,condition)=>{checks.push(name);console.log(`${condition?'OK  ':'FAIL'} ${name}`);if(!condition)failures.push(name)};
const landing=read('src/pages/store/Landing.tsx');
const storeLayout=read('src/layouts/StoreLayout.tsx');
const adminLayout=read('src/layouts/AdminLayout.tsx');
const masterLayout=read('src/layouts/MasterLayout.tsx');
const adminLogin=read('src/pages/admin/Login.tsx');
const masterLogin=read('src/pages/master/Login.tsx');
const auth=read('src/contexts/AuthContext.tsx');
const billing=read('src/services/billingFinanceApi.ts');
const edge=read('supabase/functions/flori-public-contact/index.ts');
const migration=read('supabase/migrations/202609031700_floriweb_rc6_3_public_security.sql');
const config=read('supabase/config.toml');
const css=read('src/styles.css');
ok('Landing usa contato protegido',landing.includes('ProtectedContactButton')&&landing.includes('contactProtected'));
ok('Landing nao expoe wa.me',!landing.includes('wa.me/'));
ok('Landing nao oferece suporte tecnico ao cliente final',!landing.includes('PlatformHelpButton')&&landing.includes('Suporte reservado ao lojista'));
ok('Vitrine publica nao mostra suporte da plataforma',!storeLayout.includes('PlatformHelpButton'));
ok('Admin autenticado possui ajuda interna',adminLayout.includes('PlatformHelpButton'));
ok('Master autenticado possui ajuda interna',masterLayout.includes('PlatformHelpButton'));
ok('Login Admin usa Turnstile',adminLogin.includes('action="login"')&&adminLogin.includes('captchaToken'));
ok('Login Master usa Turnstile',masterLogin.includes('action="login"')&&masterLogin.includes('captchaToken'));
ok('Auth encaminha captcha ao Supabase',auth.includes('captchaToken?: string')&&auth.includes('options: captchaToken ? { captchaToken } : undefined'));
ok('Landing RPC nao tipa telefones publicos',!billing.includes('marketingWhatsapp: data.')&&!billing.includes('supportWhatsapp: data.'));
ok('Contato publico valida Turnstile',edge.includes("result.action&&result.action!=='marketing'")&&edge.includes('TURNSTILE_SECRET_KEY'));
ok('Contato publico possui rate limit',edge.includes('enforce_public_contact_rate_limit_v1')&&migration.includes('TOO_MANY_CONTACT_ATTEMPTS'));
const publicLandingSql=migration.slice(0,migration.indexOf('create or replace function public.get_admin_support_contact_v1'));
ok('Landing publica nao retorna telefones',publicLandingSql.includes("'contact_protected',true")&&!publicLandingSql.includes("'marketing_whatsapp',")&&!publicLandingSql.includes("'support_whatsapp',")&&!publicLandingSql.includes("'billing_whatsapp',"));
ok('Config publica somente a Edge publica sem JWT',config.includes('[functions.flori-public-contact]')&&config.includes('verify_jwt = false'));
ok('CSS RC6.3 aplicado',css.includes('FloriWeb V3 RC6.3: contato protegido'));
ok('Favicon Flori distinto presente',exists('public/favicon.svg')&&read('public/favicon.svg').includes('#7d273d'));
if(failures.length){console.error(`\n${failures.length} falha(s):`);failures.forEach(f=>console.error(`- ${f}`));process.exit(1)}
console.log(`\nFloriWeb RC6.3: ${checks.length}/${checks.length} verificacoes aprovadas.`);
