-- FloriWeb V3 RC5.2
-- 1) Demo global habilitavel/desabilitavel, sem interromper Demos ja existentes.
-- 2) Recupera/garante o modulo de Analytics de conversao V3.
-- 3) Melhora o diagnostico de cron/analytics e recarrega o schema cache do PostgREST.

begin;

-- ---------------------------------------------------------------------------
-- DEMO GLOBAL
-- ---------------------------------------------------------------------------

alter table public.platform_settings
  add column if not exists demo_enabled boolean not null default true;

update public.platform_settings
set demo_enabled = true
where id = 1 and demo_enabled is null;

comment on column public.platform_settings.demo_enabled is
  'Quando false, impede novas atribuicoes ao plano DEMO. Demos ja existentes continuam ate o vencimento ou alteracao manual.';

create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

create or replace function private.enforce_demo_plan_availability()
returns trigger
language plpgsql
security definer
set search_path = public, private, pg_temp
as $$
declare
  v_demo_enabled boolean := true;
  v_new_plan_code text;
  v_old_plan_code text;
begin
  select p.code into v_new_plan_code
  from public.plans p
  where p.id = new.plan_id;

  if v_new_plan_code = 'DEMO' then
    select coalesce(ps.demo_enabled, true)
      into v_demo_enabled
    from public.platform_settings ps
    where ps.id = 1;

    if not coalesce(v_demo_enabled, true) then
      if tg_op = 'INSERT' then
        raise exception 'O acesso Demo esta desabilitado no Admin Master.' using errcode='P0001';
      end if;

      select p.code into v_old_plan_code
      from public.plans p
      where p.id = old.plan_id;

      -- Permite manter/editar uma Demo que ja existia, mas impede converter
      -- um plano pago para Demo enquanto a oferta global estiver desabilitada.
      if v_old_plan_code is distinct from 'DEMO' then
        raise exception 'O acesso Demo esta desabilitado no Admin Master.' using errcode='P0001';
      end if;
    end if;
  end if;

  return new;
end;
$$;

revoke all on function private.enforce_demo_plan_availability() from public, anon, authenticated;

drop trigger if exists store_subscriptions_demo_availability_trg on public.store_subscriptions;
create trigger store_subscriptions_demo_availability_trg
before insert or update of plan_id on public.store_subscriptions
for each row execute function private.enforce_demo_plan_availability();

-- ---------------------------------------------------------------------------
-- ANALYTICS DE CONVERSAO V3 - REPARO/ATIVACAO IDPOTENTE
-- ---------------------------------------------------------------------------

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  store_id uuid not null references public.stores(id) on delete cascade,
  session_id uuid not null,
  event_name text not null,
  product_id uuid null references public.products(id) on delete set null,
  order_id uuid null references public.orders(id) on delete set null,
  occurred_at timestamptz not null default now()
);

-- Se a tabela veio de uma tentativa parcial anterior, garante as colunas esperadas.
alter table public.analytics_events add column if not exists store_id uuid;
alter table public.analytics_events add column if not exists session_id uuid;
alter table public.analytics_events add column if not exists event_name text;
alter table public.analytics_events add column if not exists product_id uuid;
alter table public.analytics_events add column if not exists order_id uuid;
alter table public.analytics_events add column if not exists occurred_at timestamptz default now();

-- O constraint pode ja existir na RC2. Se nao existir, cria sem duplicar.
do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'analytics_events_name_ck'
      and conrelid = 'public.analytics_events'::regclass
  ) then
    alter table public.analytics_events
      add constraint analytics_events_name_ck check (event_name in (
        'storefront_view',
        'product_view',
        'add_to_cart',
        'checkout_started',
        'order_created',
        'whatsapp_clicked'
      ));
  end if;
end;
$$;

create index if not exists analytics_events_store_time_idx
  on public.analytics_events(store_id, occurred_at desc);
create index if not exists analytics_events_store_session_idx
  on public.analytics_events(store_id, session_id, occurred_at desc);
create index if not exists analytics_events_product_idx
  on public.analytics_events(store_id, product_id, occurred_at desc)
  where product_id is not null;
create index if not exists analytics_events_order_idx
  on public.analytics_events(order_id)
  where order_id is not null;
create unique index if not exists analytics_events_order_event_uidx
  on public.analytics_events(order_id, event_name)
  where order_id is not null and event_name in ('order_created','whatsapp_clicked');

alter table public.analytics_events enable row level security;
revoke all on public.analytics_events from public, anon, authenticated;

do $$
begin
  if to_regclass('public.analytics_events_id_seq') is not null then
    execute 'revoke all on sequence public.analytics_events_id_seq from public, anon, authenticated';
  end if;
end;
$$;

create or replace function public.track_public_event_v3(
  p_store_id uuid,
  p_session_id uuid,
  p_event_name text,
  p_product_id uuid default null
)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_window interval;
  v_product_id uuid := p_product_id;
begin
  if p_store_id is null or p_session_id is null then
    raise exception 'Evento invalido.' using errcode='P0001';
  end if;

  if p_event_name not in ('storefront_view','product_view','add_to_cart','checkout_started') then
    raise exception 'Evento nao permitido.' using errcode='P0001';
  end if;

  if not public.store_accessible(p_store_id) then
    return;
  end if;

  if p_event_name in ('product_view','add_to_cart') then
    if v_product_id is null or not exists (
      select 1
      from public.products p
      join public.categories c
        on c.id = p.category_id
       and c.store_id = p.store_id
      where p.id = v_product_id
        and p.store_id = p_store_id
        and p.active
        and c.active
    ) then
      raise exception 'Produto invalido para telemetria.' using errcode='P0001';
    end if;
  else
    v_product_id := null;
  end if;

  v_window := case p_event_name
    when 'storefront_view' then interval '30 minutes'
    when 'product_view' then interval '10 minutes'
    when 'add_to_cart' then interval '1 minute'
    when 'checkout_started' then interval '15 minutes'
    else interval '1 minute'
  end;

  if exists (
    select 1
    from public.analytics_events ae
    where ae.store_id = p_store_id
      and ae.session_id = p_session_id
      and ae.event_name = p_event_name
      and ae.product_id is not distinct from v_product_id
      and ae.occurred_at >= now() - v_window
  ) then
    return;
  end if;

  insert into public.analytics_events(store_id, session_id, event_name, product_id)
  values (p_store_id, p_session_id, p_event_name, v_product_id);
end;
$$;

revoke all on function public.track_public_event_v3(uuid,uuid,text,uuid) from public;
grant execute on function public.track_public_event_v3(uuid,uuid,text,uuid) to anon, authenticated;

create or replace function public.get_store_analytics_v3(
  p_store_id uuid,
  p_from timestamptz default null,
  p_to timestamptz default null
)
returns jsonb
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
declare
  v_from timestamptz := coalesce(p_from, now() - interval '30 days');
  v_to timestamptz := coalesce(p_to, now());
  v_storefront_sessions bigint := 0;
  v_product_views bigint := 0;
  v_product_view_sessions bigint := 0;
  v_add_sessions bigint := 0;
  v_checkout_sessions bigint := 0;
  v_order_sessions bigint := 0;
  v_orders bigint := 0;
  v_whatsapp bigint := 0;
  v_cart_abandoned bigint := 0;
  v_checkout_abandoned bigint := 0;
  v_revenue numeric := 0;
  v_average numeric := 0;
  v_top_products jsonb := '[]'::jsonb;
  v_viewed_not_sold jsonb := '[]'::jsonb;
begin
  if not public.is_store_admin(p_store_id) then
    raise exception 'Acesso negado.' using errcode='42501';
  end if;

  if not exists (
    select 1
    from public.store_subscriptions ss
    join public.plans p on p.id = ss.plan_id
    where ss.store_id = p_store_id
      and ss.status in ('trial','active')
      and p.active
      and p.reports
  ) then
    raise exception 'O plano atual nao inclui relatorios.' using errcode='42501';
  end if;

  if v_to > now() + interval '5 minutes' then v_to := now(); end if;
  if v_from >= v_to then raise exception 'Periodo de analytics invalido.' using errcode='P0001'; end if;
  if v_to - v_from > interval '180 days' then v_from := v_to - interval '180 days'; end if;

  select
    count(distinct session_id) filter (where event_name='storefront_view'),
    count(*) filter (where event_name='product_view'),
    count(distinct session_id) filter (where event_name='product_view'),
    count(distinct session_id) filter (where event_name='add_to_cart'),
    count(distinct session_id) filter (where event_name='checkout_started'),
    count(distinct session_id) filter (where event_name='order_created'),
    count(*) filter (where event_name='order_created'),
    count(*) filter (where event_name='whatsapp_clicked')
  into
    v_storefront_sessions,
    v_product_views,
    v_product_view_sessions,
    v_add_sessions,
    v_checkout_sessions,
    v_order_sessions,
    v_orders,
    v_whatsapp
  from public.analytics_events
  where store_id = p_store_id
    and occurred_at >= v_from
    and occurred_at < v_to;

  select count(distinct add_event.session_id)
  into v_cart_abandoned
  from public.analytics_events add_event
  where add_event.store_id = p_store_id
    and add_event.event_name='add_to_cart'
    and add_event.occurred_at >= v_from
    and add_event.occurred_at < v_to
    and not exists (
      select 1
      from public.analytics_events order_event
      where order_event.store_id = p_store_id
        and order_event.session_id = add_event.session_id
        and order_event.event_name='order_created'
        and order_event.occurred_at >= v_from
        and order_event.occurred_at < v_to
    );

  select count(distinct checkout_event.session_id)
  into v_checkout_abandoned
  from public.analytics_events checkout_event
  where checkout_event.store_id = p_store_id
    and checkout_event.event_name='checkout_started'
    and checkout_event.occurred_at >= v_from
    and checkout_event.occurred_at < v_to
    and not exists (
      select 1
      from public.analytics_events order_event
      where order_event.store_id = p_store_id
        and order_event.session_id = checkout_event.session_id
        and order_event.event_name='order_created'
        and order_event.occurred_at >= v_from
        and order_event.occurred_at < v_to
    );

  select
    coalesce(sum(o.total) filter (where o.status <> 'cancelled'),0),
    coalesce(avg(o.total) filter (where o.status <> 'cancelled'),0)
  into v_revenue, v_average
  from public.orders o
  where o.store_id = p_store_id
    and o.created_at >= v_from
    and o.created_at < v_to;

  with views as (
    select product_id, count(*)::bigint as views
    from public.analytics_events
    where store_id=p_store_id
      and event_name='product_view'
      and product_id is not null
      and occurred_at >= v_from and occurred_at < v_to
    group by product_id
  ), adds as (
    select product_id, count(distinct session_id)::bigint as add_sessions
    from public.analytics_events
    where store_id=p_store_id
      and event_name='add_to_cart'
      and product_id is not null
      and occurred_at >= v_from and occurred_at < v_to
    group by product_id
  ), sold as (
    select oi.product_id, coalesce(sum(oi.quantity),0)::bigint as sold_units
    from public.order_items oi
    join public.orders o on o.id=oi.order_id
    where o.store_id=p_store_id
      and o.status <> 'cancelled'
      and o.created_at >= v_from and o.created_at < v_to
      and oi.product_id is not null
    group by oi.product_id
  ), ranked as (
    select p.id, p.name,
      coalesce(v.views,0)::bigint as views,
      coalesce(a.add_sessions,0)::bigint as add_sessions,
      coalesce(s.sold_units,0)::bigint as sold_units
    from public.products p
    left join views v on v.product_id=p.id
    left join adds a on a.product_id=p.id
    left join sold s on s.product_id=p.id
    where p.store_id=p_store_id
      and (coalesce(v.views,0)>0 or coalesce(a.add_sessions,0)>0 or coalesce(s.sold_units,0)>0)
    order by coalesce(v.views,0) desc, coalesce(a.add_sessions,0) desc, coalesce(s.sold_units,0) desc, p.name
    limit 8
  )
  select coalesce(jsonb_agg(jsonb_build_object(
    'productId', id,
    'name', name,
    'views', views,
    'addToCartSessions', add_sessions,
    'soldUnits', sold_units
  )), '[]'::jsonb)
  into v_top_products
  from ranked;

  with views as (
    select product_id, count(*)::bigint as views
    from public.analytics_events
    where store_id=p_store_id
      and event_name='product_view'
      and product_id is not null
      and occurred_at >= v_from and occurred_at < v_to
    group by product_id
  ), adds as (
    select product_id, count(distinct session_id)::bigint as add_sessions
    from public.analytics_events
    where store_id=p_store_id
      and event_name='add_to_cart'
      and product_id is not null
      and occurred_at >= v_from and occurred_at < v_to
    group by product_id
  ), sold as (
    select oi.product_id, coalesce(sum(oi.quantity),0)::bigint as sold_units
    from public.order_items oi
    join public.orders o on o.id=oi.order_id
    where o.store_id=p_store_id
      and o.status <> 'cancelled'
      and o.created_at >= v_from and o.created_at < v_to
      and oi.product_id is not null
    group by oi.product_id
  ), ranked as (
    select p.id, p.name,
      coalesce(v.views,0)::bigint as views,
      coalesce(a.add_sessions,0)::bigint as add_sessions,
      coalesce(s.sold_units,0)::bigint as sold_units
    from public.products p
    join views v on v.product_id=p.id
    left join adds a on a.product_id=p.id
    left join sold s on s.product_id=p.id
    where p.store_id=p_store_id
      and coalesce(v.views,0)>0
      and coalesce(s.sold_units,0)=0
    order by coalesce(v.views,0) desc, coalesce(a.add_sessions,0) desc, p.name
    limit 8
  )
  select coalesce(jsonb_agg(jsonb_build_object(
    'productId', id,
    'name', name,
    'views', views,
    'addToCartSessions', add_sessions,
    'soldUnits', sold_units
  )), '[]'::jsonb)
  into v_viewed_not_sold
  from ranked;

  return jsonb_build_object(
    'from', v_from,
    'to', v_to,
    'storefrontSessions', v_storefront_sessions,
    'productViews', v_product_views,
    'productViewSessions', v_product_view_sessions,
    'addToCartSessions', v_add_sessions,
    'checkoutSessions', v_checkout_sessions,
    'orderSessions', v_order_sessions,
    'orders', v_orders,
    'whatsappClicks', v_whatsapp,
    'conversionRate', case when v_storefront_sessions>0 then round((v_order_sessions::numeric/v_storefront_sessions::numeric)*100,1) else 0 end,
    'cartAbandonmentRate', case when v_add_sessions>0 then round((v_cart_abandoned::numeric/v_add_sessions::numeric)*100,1) else 0 end,
    'checkoutAbandonmentRate', case when v_checkout_sessions>0 then round((v_checkout_abandoned::numeric/v_checkout_sessions::numeric)*100,1) else 0 end,
    'whatsappRate', case when v_orders>0 then round((v_whatsapp::numeric/v_orders::numeric)*100,1) else 0 end,
    'revenue', round(v_revenue,2),
    'averageTicket', round(v_average,2),
    'topProducts', v_top_products,
    'viewedNotSold', v_viewed_not_sold
  );
end;
$$;

revoke all on function public.get_store_analytics_v3(uuid,timestamptz,timestamptz) from public;
grant execute on function public.get_store_analytics_v3(uuid,timestamptz,timestamptz) to authenticated;

-- ---------------------------------------------------------------------------
-- DIAGNOSTICO MASTER MAIS EXPLICITO
-- ---------------------------------------------------------------------------

create or replace function public.platform_system_check()
returns jsonb
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
declare
  result jsonb;
  v_demo_enabled boolean := true;
  v_duration integer := 30;
  v_warning integer := 7;
  v_cron_exists boolean := false;
  v_cron_active boolean := false;
  v_cron_schedule text := null;
  v_analytics_ready boolean := false;
begin
  if not public.is_platform_admin() then
    raise exception 'Acesso restrito ao Admin Master.' using errcode='42501';
  end if;

  select coalesce(demo_enabled,true),demo_duration_days,demo_warning_days
    into v_demo_enabled,v_duration,v_warning
  from public.platform_settings where id=1;

  v_analytics_ready :=
    to_regclass('public.analytics_events') is not null
    and to_regprocedure('public.track_public_event_v3(uuid,uuid,text,uuid)') is not null
    and to_regprocedure('public.get_store_analytics_v3(uuid,timestamptz,timestamptz)') is not null;

  if to_regnamespace('cron') is not null then
    begin
      execute $q$
        select
          exists(select 1 from cron.job where jobname='floriweb-expire-demo-trials'),
          coalesce((select active from cron.job where jobname='floriweb-expire-demo-trials' order by jobid desc limit 1),false),
          (select schedule from cron.job where jobname='floriweb-expire-demo-trials' order by jobid desc limit 1)
      $q$ into v_cron_exists,v_cron_active,v_cron_schedule;
    exception when others then
      -- Nao derruba o diagnostico inteiro se a extensao restringir leitura de cron.job.
      v_cron_exists := false;
      v_cron_active := false;
      v_cron_schedule := null;
    end;
  end if;

  select jsonb_build_object(
    'version', '3.0.0-rc.5.2',
    'platformAdmin', true,
    'stores', (select count(*) from public.stores where archived_at is null),
    'storesOnline', (select count(*) from public.stores where archived_at is null and public.store_accessible(id)),
    'storesSuspended', (select count(*) from public.stores where archived_at is null and not public.store_accessible(id)),
    'plans', (select count(*) from public.plans),
    'subscriptions', (select count(*) from public.store_subscriptions),
    'users', (select count(*) from public.store_users),
    'products', (select count(*) from public.products),
    'orders', (select count(*) from public.orders),
    'deliveryZones', (select count(*) from public.delivery_zones),
    'domains', (select count(*) from public.store_domains),
    'analyticsEvents', case when to_regclass('public.analytics_events') is not null then (select count(*) from public.analytics_events) else 0 end,
    'analyticsReady', v_analytics_ready,
    'demoEnabled', v_demo_enabled,
    'demoTrials', (
      select count(*) from public.store_subscriptions ss
      join public.plans p on p.id=ss.plan_id
      where p.code='DEMO' and ss.status='trial'
    ),
    'demoTrialsExpiringSoon', (
      select count(*) from public.store_subscriptions ss
      join public.plans p on p.id=ss.plan_id
      where p.code='DEMO' and ss.status='trial' and ss.expires_at is not null
        and ss.expires_at > now()
        and ss.expires_at <= now() + make_interval(days => v_warning)
    ),
    'demoDurationDays', v_duration,
    'demoWarningDays', v_warning,
    'demoCronScheduled', v_cron_exists and v_cron_active,
    'demoCronExists', v_cron_exists,
    'demoCronActive', v_cron_active,
    'demoCronSchedule', v_cron_schedule
  ) into result;

  return result;
end;
$$;

revoke all on function public.platform_system_check() from public;
grant execute on function public.platform_system_check() to authenticated;

-- Forca o PostgREST a enxergar imediatamente as novas/recuperadas RPCs.
notify pgrst, 'reload schema';

commit;
