-- FloriWeb V3 RC1 - rate limit de pedidos publicos
-- Mantem somente um hash efemero do IP para finalidade de seguranca/anti-abuso.
-- Nenhum IP bruto, nome, telefone, endereco ou conteudo do pedido e gravado nesta tabela.

begin;

create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

create table if not exists private.floriweb_security_settings (
  key text primary key,
  value text not null,
  created_at timestamptz not null default now()
);

insert into private.floriweb_security_settings(key,value)
values ('public_order_rate_limit_salt', gen_random_uuid()::text)
on conflict(key) do nothing;

create table if not exists private.public_order_rate_limits (
  id bigint generated by default as identity primary key,
  store_id uuid not null references public.stores(id) on delete cascade,
  fingerprint text not null,
  request_at timestamptz not null default now()
);

create index if not exists public_order_rate_limits_lookup_idx
  on private.public_order_rate_limits(store_id,fingerprint,request_at desc);

revoke all on all tables in schema private from public, anon, authenticated;
revoke all on all sequences in schema private from public, anon, authenticated;

create or replace function public.enforce_public_order_rate_limit(p_store_id uuid)
returns void
language plpgsql
security definer
set search_path = public, private, pg_temp
as $$
declare
  v_headers jsonb := '{}'::jsonb;
  v_ip text := '';
  v_salt text := '';
  v_fingerprint text;
  v_count integer := 0;
begin
  -- current_setting(..., true) e o contexto HTTP oficial disponibilizado pelo PostgREST.
  begin
    v_headers := coalesce(nullif(current_setting('request.headers', true), '')::jsonb, '{}'::jsonb);
  exception when others then
    v_headers := '{}'::jsonb;
  end;

  v_ip := nullif(trim(coalesce(v_headers->>'cf-connecting-ip','')), '');
  if v_ip is null then
    v_ip := nullif(trim(split_part(coalesce(v_headers->>'x-forwarded-for',''), ',', 1)), '');
  end if;

  -- Chamadas internas/SQL Editor podem nao possuir contexto HTTP; nesse caso o helper
  -- nao interfere na operacao. O checkout publico via PostgREST possui request.headers.
  if v_ip is null then
    return;
  end if;

  select value into v_salt
  from private.floriweb_security_settings
  where key='public_order_rate_limit_salt';

  if coalesce(v_salt,'') = '' then
    raise exception 'Configuracao interna de seguranca ausente.' using errcode='P0001';
  end if;

  -- Salt privado evita armazenar ou expor o IP original. O hash existe apenas para
  -- agrupar tentativas no curto periodo de protecao.
  v_fingerprint := md5(v_ip || ':' || v_salt);

  -- Serializa tentativas simultaneas do mesmo fingerprint/loja.
  perform pg_advisory_xact_lock(hashtextextended(p_store_id::text || ':' || v_fingerprint, 0));

  select count(*) into v_count
  from private.public_order_rate_limits rl
  where rl.store_id = p_store_id
    and rl.fingerprint = v_fingerprint
    and rl.request_at >= now() - interval '10 minutes';

  if v_count >= 8 then
    raise exception 'Muitas tentativas de pedido em pouco tempo. Aguarde alguns minutos e tente novamente.' using errcode='P0001';
  end if;

  insert into private.public_order_rate_limits(store_id,fingerprint)
  values (p_store_id,v_fingerprint);

  -- Retencao curta: registros servem somente ao anti-abuso e sao descartados apos 24 h.
  delete from private.public_order_rate_limits
  where request_at < now() - interval '24 hours';
end;
$$;

revoke all on function public.enforce_public_order_rate_limit(uuid) from public, anon, authenticated;

commit;
