-- FloriWeb V3 RC2 - Analytics de conversao sem PII
-- Armazena somente loja, sessao anonima, evento, produto/pedido e horario.
-- Nao grava nome, telefone, e-mail, endereco, mensagem do cartao, observacoes ou IP.

begin;

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  store_id uuid not null references public.stores(id) on delete cascade,
  session_id uuid not null,
  event_name text not null,
  product_id uuid null references public.products(id) on delete set null,
  order_id uuid null references public.orders(id) on delete set null,
  occurred_at timestamptz not null default now(),
  constraint analytics_events_name_ck check (event_name in (
    'storefront_view',
    'product_view',
    'add_to_cart',
    'checkout_started',
    'order_created',
    'whatsapp_clicked'
  ))
);

create index if not exists analytics_events_store_time_idx
  on public.analytics_events(store_id, occurred_at desc);
create index if not exists analytics_events_store_session_idx
  on public.analytics_events(store_id, session_id, occurred_at desc);
create index if not exists analytics_events_product_idx
  on public.analytics_events(store_id, product_id, occurred_at desc)
  where product_id is not null;
create index if not exists analytics_events_order_idx
  on public.analytics_events(order_id)
  where order_id is not null;
create unique index if not exists analytics_events_order_event_uidx
  on public.analytics_events(order_id, event_name)
  where order_id is not null and event_name in ('order_created','whatsapp_clicked');

alter table public.analytics_events enable row level security;
revoke all on public.analytics_events from public, anon, authenticated;
revoke all on sequence public.analytics_events_id_seq from public, anon, authenticated;

-- Eventos de navegacao aceitos do storefront. A funcao faz deduplicacao de curto prazo
-- para evitar inflar metricas por re-render/reload acidental da SPA.
create or replace function public.track_public_event_v3(
  p_store_id uuid,
  p_session_id uuid,
  p_event_name text,
  p_product_id uuid default null
)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_window interval;
  v_product_id uuid := p_product_id;
begin
  if p_store_id is null or p_session_id is null then
    raise exception 'Evento invalido.' using errcode='P0001';
  end if;

  if p_event_name not in ('storefront_view','product_view','add_to_cart','checkout_started') then
    raise exception 'Evento nao permitido.' using errcode='P0001';
  end if;

  if not public.store_accessible(p_store_id) then
    return;
  end if;

  if p_event_name in ('product_view','add_to_cart') then
    if v_product_id is null or not exists (
      select 1
      from public.products p
      join public.categories c
        on c.id = p.category_id
       and c.store_id = p.store_id
      where p.id = v_product_id
        and p.store_id = p_store_id
        and p.active
        and c.active
    ) then
      raise exception 'Produto invalido para telemetria.' using errcode='P0001';
    end if;
  else
    v_product_id := null;
  end if;

  v_window := case p_event_name
    when 'storefront_view' then interval '30 minutes'
    when 'product_view' then interval '10 minutes'
    when 'add_to_cart' then interval '1 minute'
    when 'checkout_started' then interval '15 minutes'
    else interval '1 minute'
  end;

  if exists (
    select 1
    from public.analytics_events ae
    where ae.store_id = p_store_id
      and ae.session_id = p_session_id
      and ae.event_name = p_event_name
      and ae.product_id is not distinct from v_product_id
      and ae.occurred_at >= now() - v_window
  ) then
    return;
  end if;

  insert into public.analytics_events(store_id, session_id, event_name, product_id)
  values (p_store_id, p_session_id, p_event_name, v_product_id);
end;
$$;

revoke all on function public.track_public_event_v3(uuid,uuid,text,uuid) from public;
grant execute on function public.track_public_event_v3(uuid,uuid,text,uuid) to anon, authenticated;

-- Relatorio agregado: somente administradores da propria loja e apenas em plano com reports=true.
create or replace function public.get_store_analytics_v3(
  p_store_id uuid,
  p_from timestamptz default null,
  p_to timestamptz default null
)
returns jsonb
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
declare
  v_from timestamptz := coalesce(p_from, now() - interval '30 days');
  v_to timestamptz := coalesce(p_to, now());
  v_storefront_sessions bigint := 0;
  v_product_views bigint := 0;
  v_product_view_sessions bigint := 0;
  v_add_sessions bigint := 0;
  v_checkout_sessions bigint := 0;
  v_order_sessions bigint := 0;
  v_orders bigint := 0;
  v_whatsapp bigint := 0;
  v_cart_abandoned bigint := 0;
  v_checkout_abandoned bigint := 0;
  v_revenue numeric := 0;
  v_average numeric := 0;
  v_top_products jsonb := '[]'::jsonb;
  v_viewed_not_sold jsonb := '[]'::jsonb;
begin
  if not public.is_store_admin(p_store_id) then
    raise exception 'Acesso negado.' using errcode='42501';
  end if;

  if not exists (
    select 1
    from public.store_subscriptions ss
    join public.plans p on p.id = ss.plan_id
    where ss.store_id = p_store_id
      and ss.status in ('trial','active')
      and p.active
      and p.reports
  ) then
    raise exception 'O plano atual nao inclui relatorios.' using errcode='42501';
  end if;

  if v_to > now() + interval '5 minutes' then v_to := now(); end if;
  if v_from >= v_to then raise exception 'Periodo de analytics invalido.' using errcode='P0001'; end if;
  if v_to - v_from > interval '180 days' then v_from := v_to - interval '180 days'; end if;

  select
    count(distinct session_id) filter (where event_name='storefront_view'),
    count(*) filter (where event_name='product_view'),
    count(distinct session_id) filter (where event_name='product_view'),
    count(distinct session_id) filter (where event_name='add_to_cart'),
    count(distinct session_id) filter (where event_name='checkout_started'),
    count(distinct session_id) filter (where event_name='order_created'),
    count(*) filter (where event_name='order_created'),
    count(*) filter (where event_name='whatsapp_clicked')
  into
    v_storefront_sessions,
    v_product_views,
    v_product_view_sessions,
    v_add_sessions,
    v_checkout_sessions,
    v_order_sessions,
    v_orders,
    v_whatsapp
  from public.analytics_events
  where store_id = p_store_id
    and occurred_at >= v_from
    and occurred_at < v_to;

  select count(distinct add_event.session_id)
  into v_cart_abandoned
  from public.analytics_events add_event
  where add_event.store_id = p_store_id
    and add_event.event_name='add_to_cart'
    and add_event.occurred_at >= v_from
    and add_event.occurred_at < v_to
    and not exists (
      select 1
      from public.analytics_events order_event
      where order_event.store_id = p_store_id
        and order_event.session_id = add_event.session_id
        and order_event.event_name='order_created'
        and order_event.occurred_at >= v_from
        and order_event.occurred_at < v_to
    );

  select count(distinct checkout_event.session_id)
  into v_checkout_abandoned
  from public.analytics_events checkout_event
  where checkout_event.store_id = p_store_id
    and checkout_event.event_name='checkout_started'
    and checkout_event.occurred_at >= v_from
    and checkout_event.occurred_at < v_to
    and not exists (
      select 1
      from public.analytics_events order_event
      where order_event.store_id = p_store_id
        and order_event.session_id = checkout_event.session_id
        and order_event.event_name='order_created'
        and order_event.occurred_at >= v_from
        and order_event.occurred_at < v_to
    );

  select
    coalesce(sum(o.total) filter (where o.status <> 'cancelled'),0),
    coalesce(avg(o.total) filter (where o.status <> 'cancelled'),0)
  into v_revenue, v_average
  from public.orders o
  where o.store_id = p_store_id
    and o.created_at >= v_from
    and o.created_at < v_to;

  with views as (
    select product_id, count(*)::bigint as views
    from public.analytics_events
    where store_id=p_store_id
      and event_name='product_view'
      and product_id is not null
      and occurred_at >= v_from and occurred_at < v_to
    group by product_id
  ), adds as (
    select product_id, count(distinct session_id)::bigint as add_sessions
    from public.analytics_events
    where store_id=p_store_id
      and event_name='add_to_cart'
      and product_id is not null
      and occurred_at >= v_from and occurred_at < v_to
    group by product_id
  ), sold as (
    select oi.product_id, coalesce(sum(oi.quantity),0)::bigint as sold_units
    from public.order_items oi
    join public.orders o on o.id=oi.order_id
    where o.store_id=p_store_id
      and o.status <> 'cancelled'
      and o.created_at >= v_from and o.created_at < v_to
      and oi.product_id is not null
    group by oi.product_id
  ), ranked as (
    select p.id, p.name,
      coalesce(v.views,0)::bigint as views,
      coalesce(a.add_sessions,0)::bigint as add_sessions,
      coalesce(s.sold_units,0)::bigint as sold_units
    from public.products p
    left join views v on v.product_id=p.id
    left join adds a on a.product_id=p.id
    left join sold s on s.product_id=p.id
    where p.store_id=p_store_id
      and (coalesce(v.views,0)>0 or coalesce(a.add_sessions,0)>0 or coalesce(s.sold_units,0)>0)
    order by coalesce(v.views,0) desc, coalesce(a.add_sessions,0) desc, coalesce(s.sold_units,0) desc, p.name
    limit 8
  )
  select coalesce(jsonb_agg(jsonb_build_object(
    'productId', id,
    'name', name,
    'views', views,
    'addToCartSessions', add_sessions,
    'soldUnits', sold_units
  )), '[]'::jsonb)
  into v_top_products
  from ranked;

  with views as (
    select product_id, count(*)::bigint as views
    from public.analytics_events
    where store_id=p_store_id
      and event_name='product_view'
      and product_id is not null
      and occurred_at >= v_from and occurred_at < v_to
    group by product_id
  ), adds as (
    select product_id, count(distinct session_id)::bigint as add_sessions
    from public.analytics_events
    where store_id=p_store_id
      and event_name='add_to_cart'
      and product_id is not null
      and occurred_at >= v_from and occurred_at < v_to
    group by product_id
  ), sold as (
    select oi.product_id, coalesce(sum(oi.quantity),0)::bigint as sold_units
    from public.order_items oi
    join public.orders o on o.id=oi.order_id
    where o.store_id=p_store_id
      and o.status <> 'cancelled'
      and o.created_at >= v_from and o.created_at < v_to
      and oi.product_id is not null
    group by oi.product_id
  ), ranked as (
    select p.id, p.name,
      coalesce(v.views,0)::bigint as views,
      coalesce(a.add_sessions,0)::bigint as add_sessions,
      coalesce(s.sold_units,0)::bigint as sold_units
    from public.products p
    join views v on v.product_id=p.id
    left join adds a on a.product_id=p.id
    left join sold s on s.product_id=p.id
    where p.store_id=p_store_id
      and coalesce(v.views,0)>0
      and coalesce(s.sold_units,0)=0
    order by coalesce(v.views,0) desc, coalesce(a.add_sessions,0) desc, p.name
    limit 8
  )
  select coalesce(jsonb_agg(jsonb_build_object(
    'productId', id,
    'name', name,
    'views', views,
    'addToCartSessions', add_sessions,
    'soldUnits', sold_units
  )), '[]'::jsonb)
  into v_viewed_not_sold
  from ranked;

  return jsonb_build_object(
    'from', v_from,
    'to', v_to,
    'storefrontSessions', v_storefront_sessions,
    'productViews', v_product_views,
    'productViewSessions', v_product_view_sessions,
    'addToCartSessions', v_add_sessions,
    'checkoutSessions', v_checkout_sessions,
    'orderSessions', v_order_sessions,
    'orders', v_orders,
    'whatsappClicks', v_whatsapp,
    'conversionRate', case when v_storefront_sessions>0 then round((v_order_sessions::numeric/v_storefront_sessions::numeric)*100,1) else 0 end,
    'cartAbandonmentRate', case when v_add_sessions>0 then round((v_cart_abandoned::numeric/v_add_sessions::numeric)*100,1) else 0 end,
    'checkoutAbandonmentRate', case when v_checkout_sessions>0 then round((v_checkout_abandoned::numeric/v_checkout_sessions::numeric)*100,1) else 0 end,
    'whatsappRate', case when v_orders>0 then round((v_whatsapp::numeric/v_orders::numeric)*100,1) else 0 end,
    'revenue', round(v_revenue,2),
    'averageTicket', round(v_average,2),
    'topProducts', v_top_products,
    'viewedNotSold', v_viewed_not_sold
  );
end;
$$;

revoke all on function public.get_store_analytics_v3(uuid,timestamptz,timestamptz) from public;
grant execute on function public.get_store_analytics_v3(uuid,timestamptz,timestamptz) to authenticated;

commit;
