import { CheckCircle2, Clipboard, MessageCircle, RefreshCw, Sparkles, WalletCards } from 'lucide-react';
import { useEffect,useMemo,useState } from 'react';
import { useStore } from '../../contexts/StoreContext';
import { buildPixCopyPasteWithAmount,buildStaticPixCopyPaste } from '../../utils/pix';
import { createManualCharge,loadBillingOverview,markProofSent,type BillingOverview,type SubscriptionPayment } from '../../services/billingFinanceApi';

const money=(v:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(v);
export default function Billing(){const{settings}=useStore();const[data,setData]=useState<BillingOverview|null>(null);const[busy,setBusy]=useState('');const[error,setError]=useState('');const load=()=>loadBillingOverview(settings.id).then(setData).catch((e:unknown)=>setError(e instanceof Error?e.message:'Falha ao carregar cobrança.'));useEffect(()=>{if(settings.id)void load()},[settings.id]);
const pending=useMemo(()=>data?.payments.find(p=>p.status==='pending'||p.status==='proof_sent'),[data]);
const pixFor=(p:SubscriptionPayment)=>{if(!data)return '';try{return data.settings.pixCopyPaste?buildPixCopyPasteWithAmount(data.settings.pixCopyPaste,p.amount):buildStaticPixCopyPaste({key:data.settings.pixKey,receiver:data.settings.pixHolderName,city:data.settings.pixCity,amount:p.amount,txid:p.id.replace(/-/g,'').slice(0,25)})}catch{return ''}};
const request=async(planId:string)=>{setBusy(planId);setError('');try{setData(await createManualCharge(settings.id,planId))}catch(e){setError(e instanceof Error?e.message:'Não foi possível criar a cobrança.')}finally{setBusy('')}};
const proof=async(p:SubscriptionPayment)=>{if(!data)return;const phone=data.settings.whatsapp.replace(/\D/g,'');if(!phone){setError('O WhatsApp financeiro ainda não foi cadastrado pelo Admin Master.');return}const current=data.currentPlan?.name||'Plano atual';const target=data.plans.find(x=>x.id===p.requestedPlanId)?.name||data.plans.find(x=>x.id===p.planId)?.name||'Plano';const message=p.paymentIntent==='plan_change'?`Olá! Realizei o pagamento e gostaria de alterar o plano da floricultura ${settings.name} de ${current} para ${target}. Valor ${money(p.amount)}. Cobrança #${p.id.slice(0,8)}. Estou enviando o comprovante.`:`Olá! Realizei o pagamento da mensalidade da floricultura ${settings.name}. Plano ${target}. Valor ${money(p.amount)}. Cobrança #${p.id.slice(0,8)}. Estou enviando o comprovante.`;window.open(`https://wa.me/55${phone.replace(/^55/,'')}?text=${encodeURIComponent(message)}`,'_blank','noopener,noreferrer');setData(await markProofSent(p.id))};
return <><div className="admin-page-title"><div><span className="eyebrow">MENSALIDADE</span><h1>Plano e pagamento por PIX</h1><p>Renove ou mude de plano e envie o comprovante diretamente para o financeiro da plataforma.</p></div><button className="secondary-button" onClick={()=>void load()}><RefreshCw size={16}/>Atualizar</button></div>{error&&<div className="form-error">{error}</div>}{!data?<div className="admin-card">Carregando...</div>:<>
<section className="admin-card flori-current-plan"><span>PLANO ATUAL</span><h2>{data.currentPlan?.name||'Sem plano ativo'}</h2><strong>{money(data.currentPlan?.monthlyPrice||0)}/mês</strong></section>
<div className="flori-admin-plan-grid">{data.plans.map(plan=><article className={`admin-card ${data.currentPlan?.id===plan.id?'current':''}`} key={plan.id}><small>{plan.code}</small><h2>{plan.name}</h2><strong>{money(plan.monthlyPrice)}<span>/mês</span></strong><p>{plan.code==='BASIC'?'Catálogo e pedidos para começar.':plan.code==='PRO'?'Mais recursos para crescer e analisar.':'Estrutura completa para operações avançadas.'}</p><button className="primary-button" disabled={Boolean(busy)||pending?.requestedPlanId===plan.id} onClick={()=>void request(plan.id)}>{busy===plan.id?'Gerando...':data.currentPlan?.id===plan.id?'Renovar com PIX':'Mudar para este plano'}</button></article>)}</div>
{pending&&<section className="admin-card flori-payment-card"><div className="admin-card__header"><div><span className="eyebrow">PAGAMENTO PENDENTE</span><h2>{pending.paymentIntent==='plan_change'?'Alteração de plano':'Renovação da mensalidade'}</h2></div><WalletCards/></div><div className="flori-payment-value"><span>Valor</span><strong>{money(pending.amount)}</strong></div>{pixFor(pending)?<><label>PIX Copia e Cola</label><div className="flori-copy-row"><textarea readOnly value={pixFor(pending)}/><button onClick={()=>void navigator.clipboard.writeText(pixFor(pending))}><Clipboard size={16}/>Copiar</button></div></>:<div className="form-error">Cadastre uma Chave PIX válida ou PIX Copia e Cola base no Admin Master.</div>}<div className="flori-proof-step"><MessageCircle/><div><strong>Envio do comprovante é obrigatório</strong><p>Depois de pagar, abra o WhatsApp, anexe o comprovante e aguarde a conferência do Admin Master.</p></div><button className="primary-button" onClick={()=>void proof(pending)}>{pending.status==='proof_sent'?<><CheckCircle2 size={16}/>Comprovante informado</>:<>Enviar comprovante no WhatsApp</>}</button></div></section>}
<section className="admin-card flori-billing-note"><Sparkles/><div><strong>Pagamento seguro e simples</strong><p>O valor é obtido do plano cadastrado na plataforma. A ativação só acontece após a conferência manual do PIX e do comprovante.</p></div></section></>}</>}
