import { Edit3, Eye, EyeOff, Plus, Search, Trash2 } from 'lucide-react';
import { useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { ImageWithFallback } from '../../components/ui/ImageWithFallback';
import { ErrorState, LoadingState } from '../../components/ui/AsyncState';
import { useStore } from '../../contexts/StoreContext';
import { useToast } from '../../contexts/ToastContext';
import { currency } from '../../utils/format';

export default function ProductsAdmin(){
  const {products,categories,deleteProduct,saveProduct,planUsage,loading,error,reloadAdmin}=useStore();const{showToast}=useToast();const[query,setQuery]=useState('');const[busyId,setBusyId]=useState('');const filtered=useMemo(()=>products.filter(p=>p.name.toLowerCase().includes(query.toLowerCase())),[products,query]);
  if(loading)return <LoadingState label="Carregando produtos..."/>;if(error)return <ErrorState message={error} onRetry={()=>void reloadAdmin()}/>;
  const toggle=async(id:string)=>{const p=products.find(x=>x.id===id);if(!p)return;setBusyId(id);try{await saveProduct({...p,active:!p.active});showToast(`Produto ${p.active?'ocultado':'ativado'}.`,'success')}catch(e){showToast(e instanceof Error?e.message:'Erro ao atualizar.','error')}finally{setBusyId('')}};
  const remove=async(id:string,name:string)=>{if(!confirm(`Excluir ${name}? Esta ação também removerá imagens e variações do banco.`))return;setBusyId(id);try{await deleteProduct(id);showToast('Produto removido.','success')}catch(e){showToast(e instanceof Error?e.message:'Erro ao excluir produto.','error')}finally{setBusyId('')}};
  const activeCount=products.filter((product)=>product.active).length;const limit=planUsage.plan.productLimit;return <><div className="admin-page-title"><div><span className="eyebrow">CATÁLOGO</span><h1>Produtos</h1><p>Cadastre à vontade e controle quais itens ficam publicados. O plano limita apenas os produtos ativos.</p></div><Link className="primary-button" to="/admin/produtos/novo"><Plus size={18}/>Novo produto</Link></div><div className="catalog-limit-banner"><div><strong>{activeCount}/{limit??'∞'} produtos ativos</strong><span>{limit==null?'Sem limite de publicação neste plano.':planUsage.canActivateProduct?`Você ainda pode publicar ${Math.max(0,limit-activeCount)} produto(s).`:'Limite de publicação atingido. Cadastre novos produtos como ocultos ou desative um item ativo.'}</span></div>{limit!=null&&<div className="catalog-limit-track"><span style={{width:`${Math.min(100,(activeCount/limit)*100)}%`}} /></div>}</div><section className="admin-card no-padding"><div className="table-toolbar"><div className="admin-search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar produto..."/></div><span>{filtered.length} itens</span></div><div className="responsive-table"><table><thead><tr><th>Produto</th><th>Categoria</th><th>Preço</th><th>Status</th><th></th></tr></thead><tbody>{filtered.map(product=>{const category=categories.find(c=>c.id===product.categoryId);return <tr key={product.id}><td><div className="product-cell"><ImageWithFallback src={product.imageUrl} alt={product.name}/><div><strong>{product.name}</strong><span>{product.madeToOrder?`Sob encomenda · ${product.productionDays||'-'} dias`:product.stockStatus==='unavailable'?'Indisponível':'Produto padrão'}</span></div></div></td><td>{category?.name??'—'}</td><td><strong>{currency.format(product.promotionalPrice??product.price)}</strong>{product.promotionalPrice!=null&&<small><del>{currency.format(product.price)}</del></small>}</td><td><button disabled={busyId===product.id} className={`status-toggle ${product.active?'on':'off'}`} onClick={()=>void toggle(product.id)}>{product.active?<Eye size={14}/>:<EyeOff size={14}/>} {product.active?'Ativo':'Oculto'}</button></td><td><div className="row-actions"><Link to={`/admin/produtos/${product.id}`} aria-label={`Editar ${product.name}`}><Edit3 size={17}/></Link><button disabled={busyId===product.id} onClick={()=>void remove(product.id,product.name)} aria-label={`Excluir ${product.name}`}><Trash2 size={17}/></button></div></td></tr>})}</tbody></table></div></section></>;
}
